version: '3.8'
services:
  carbooksy.api:
    image: ${DOCKER_REGISTRY-}carbooksyapi
    build:
      context: .
      dockerfile: CarBooksy.Api/Dockerfile
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: car_booksy
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80

volumes:
  postgres_data: {}